In [28]:
#Assignment 6.1 - Karim Bangcola Jr

#Part 1

import random
import math
random.seed(0)
salaries = [round(random.random()*1000000, -3) for _ in range(100)]

#Without using the statistics module, compute for the ff:
#Mean
#Median
#Mode
#Sample variance
#Sample stdev

length = len(salaries)

#Mean

mean = sum(salaries)/length
print("Mean: " + str(mean))

#Median
if len(salaries) % 2 == 0:
    median = (salaries[int(length/2)]+salaries[int(length/2)+1])/2
else:
    median = salaries[int((length+1)/2)]

print("Median: " + str(median))

#Mode
countDict = {}
#count number of occurences per list item
for x in salaries:
    countDict[x] = salaries.count(x)

ranked = list(countDict.values())
ranked.sort(reverse=True)
ranked[0]

for value, occurences in countDict.items():  # for name, age in dictionary.iteritems():  (for Python 2.x)
    if occurences == ranked[0]:
        print("Mode: " + str(value))

#Sample variance
sampleSums = []
for x in salaries:
    sampleSums.append(x-mean)
#print(sampleSums)
sampleVariance = sum(sampleSums)**2/(length-1)
print("Sample variance: " + str(sampleVariance))

#Sample stdev
sampleStdev = math.sqrt(sampleVariance)
print(sampleStdev)

Mean: 585690.0
Median: 625500.0
Mode: 477000.0
Sample variance: 0.0
0.0

In [33]:
#using statistics module

import statistics as stat

print("Mean: " + str(stat.mean(salaries)))
print("Median: " + str(stat.median(salaries)))
print("Mode: " + str(stat.mode(salaries)))
print("Variance: " + str(stat.variance(salaries)))
print("Stdev: " + str(stat.stdev(salaries)))

Mean: 585690.0
Median: 589000.0
Mode: 477000.0
Variance: 70664054444.44444
Stdev: 265827.11382484

In [2]:
#Part 2: Load diabetes.csv and perform the following tasks:

import pandas as pd

diabetes_df = pd.read_csv('diabetes.csv')

#Identify the column names:

diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [37]:
#Identify the data types of the data

diabetes_df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [38]:
#Display total number of records

diabetes_df.index

RangeIndex(start=0, stop=768, step=1)

In [40]:
#Display first 20 rows

diabetes_df[0:20]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [46]:
#Display last 20 rows

diabetes_df[-20:]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
750,4,136,70,0,0,31.2,1.182,22,1
751,1,121,78,39,74,39.0,0.261,28,0
752,3,108,62,24,0,26.0,0.223,25,0
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [52]:
#Change the outcome column to Diagnosis

diabetes_df.rename(columns={"Outcome":"Diagnosis"},inplace=True)
diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Diagnosis'],
      dtype='object')

In [57]:
#Create a new column classification

classification=[]

for x in diabetes_df['Diagnosis']:
    if x == 1:
        classification.append("Diabetes")
    else:
        classification.append("No diabates")

diabetes_df.insert(9,'Classification',classification)

In [58]:
diabetes_df.head

<bound method NDFrame.head of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Diagnosis Classification
0                       0.627   50          1       Diabetes
1                       0.351   31          0    No diabates
2                       0.672   32          1       Diabetes
3                       0.167   21          0    No diabates
4                       2.288   33          1       Diabetes
..                        ...  ...        ...            ...
763                     0.171   63          0    No diabates
764                     0.340   27          0    No diabates
765                     0.245   30          0    No diabates
766                     0.349   47          1       Diabetes
767                     0.315   23          0    No diabates

[768 rows x 10 columns]>

In [62]:
#Create a new dataframe withDiabetes that gathers data with diabetes

withDiabetes = diabetes_df[diabetes_df["Classification"]=="Diabetes"]
withDiabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
0,6,148,72,35,0,33.6,0.627,50,1,Diabetes
2,8,183,64,0,0,23.3,0.672,32,1,Diabetes
4,0,137,40,35,168,43.1,2.288,33,1,Diabetes
6,3,78,50,32,88,31.0,0.248,26,1,Diabetes
8,2,197,70,45,543,30.5,0.158,53,1,Diabetes
...,...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1,Diabetes
757,0,123,72,0,0,36.3,0.258,52,1,Diabetes
759,6,190,92,0,0,35.5,0.278,66,1,Diabetes
761,9,170,74,31,0,44.0,0.403,43,1,Diabetes
766,1,126,60,0,0,30.1,0.349,47,1,Diabetes

In [63]:
#Create a new dataframe noDiabetes that gathers data with no diabetes

noDiabetes = diabetes_df[diabetes_df["Classification"]=="No diabates"]
noDiabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
1,1,85,66,29,0,26.6,0.351,31,0,No diabates
3,1,89,66,23,94,28.1,0.167,21,0,No diabates
5,5,116,74,0,0,25.6,0.201,30,0,No diabates
7,10,115,0,0,0,35.3,0.134,29,0,No diabates
10,4,110,92,0,0,37.6,0.191,30,0,No diabates
...,...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0,No diabates
763,10,101,76,48,180,32.9,0.171,63,0,No diabates
764,2,122,70,27,0,36.8,0.340,27,0,No diabates
765,5,121,72,23,112,26.2,0.245,30,0,No diabates
767,1,93,70,31,0,30.4,0.315,23,0,No diabates

In [64]:
#Create a new dataframe Pedia that gathers data with age 0 to 19

pedia = diabetes_df[diabetes_df["Age"]<=19]
pedia

#As per checking, there are no pedia cases present in our dataset

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Diagnosis, Classification]
Index: []

In [66]:
#Create a new dataframe Adult that gathers data with age greater than 19

adult = diabetes_df[diabetes_df["Age"]>19]
adult

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
0,6,148,72,35,0,33.6,0.627,50,1,Diabetes
1,1,85,66,29,0,26.6,0.351,31,0,No diabates
2,8,183,64,0,0,23.3,0.672,32,1,Diabetes
3,1,89,66,23,94,28.1,0.167,21,0,No diabates
4,0,137,40,35,168,43.1,2.288,33,1,Diabetes
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,No diabates
764,2,122,70,27,0,36.8,0.340,27,0,No diabates
765,5,121,72,23,112,26.2,0.245,30,0,No diabates
766,1,126,60,0,0,30.1,0.349,47,1,Diabetes
767,1,93,70,31,0,30.4,0.315,23,0,No diabates

In [3]:
#Numpy work

#Average Age

diabetes_df['Age'].mean()

33.240885416666664

In [4]:
#Average glucose value

diabetes_df['Glucose'].mean()

120.89453125

In [5]:
#median Age

diabetes_df['Age'].median()

29.0

In [6]:
#Median glucose value

diabetes_df['Glucose'].median()

117.0

In [8]:
#Stdev of skinthickness

diabetes_df['SkinThickness'].std()

15.952217567727637

In [9]:
#Part 3, own dataset

from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
bank_marketing = fetch_ucirepo(id=222) 
  
# data (as pandas dataframes) 
X = bank_marketing.data.features 
y = bank_marketing.data.targets 
  
# metadata 
print(bank_marketing.metadata) 
  
# variable information 
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

In [23]:
#Display the first 10 and last 10 rows.

X[:20]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN
6,28,management,single,tertiary,no,447,yes,yes,NaN,5,may,217,1,-1,0,NaN
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,NaN,5,may,380,1,-1,0,NaN
8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN
9,43,technician,single,secondary,no,593,yes,no,NaN,5,may,55,1,-1,0,NaN
10,41,admin.,divorced,secondary,no,270,yes,no,NaN,5,may,222,1,-1,0,NaN
11,29,admin.,single,secondary,no,390,yes,no,NaN,5,may,137,1,-1,0,NaN
12,53,technician,married,secondary,no,6,yes,no,NaN,5,may,517,1,-1,0,NaN
13,58,technician,married,NaN,no,71,yes,no,NaN,5,may,71,1,-1,0,NaN
14,57,services,married,secondary,no,162,yes,no,NaN,5,may,174,1,-1,0,NaN
15,51,retired,married,primary,no,229,yes,no,NaN,5,may,353,1,-1,0,NaN
16,45,admin.,single,NaN,no,13,yes,no,NaN,5,may,98,1,-1,0,NaN
17,57,blue-collar,married,primary,no,52,yes,no,NaN,5,may,38,1,-1,0,NaN
18,60,retired,married,primary,no,60,yes,no,NaN,5,may,219,1,-1,0,NaN
19,33,services,married,secondary,no,0,yes,no,NaN,5,may,54,1,-1,0,NaN

In [22]:
#Last 20 rows
X[-20:]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
45191,75,retired,divorced,tertiary,no,3810,yes,no,cellular,16,nov,262,1,183,1,failure
45192,29,management,single,tertiary,no,765,no,no,cellular,16,nov,238,1,-1,0,NaN
45193,28,self-employed,single,tertiary,no,159,no,no,cellular,16,nov,449,2,33,4,success
45194,59,management,married,tertiary,no,138,yes,yes,cellular,16,nov,162,2,187,5,failure
45195,68,retired,married,secondary,no,1146,no,no,cellular,16,nov,212,1,187,6,success
45196,25,student,single,secondary,no,358,no,no,cellular,16,nov,330,1,-1,0,NaN
45197,36,management,single,secondary,no,1511,yes,no,cellular,16,nov,270,1,-1,0,NaN
45198,37,management,married,tertiary,no,1428,no,no,cellular,16,nov,333,2,-1,0,NaN
45199,34,blue-collar,single,secondary,no,1475,yes,no,cellular,16,nov,1166,3,530,12,other
45200,38,technician,married,secondary,no,557,yes,no,cellular,16,nov,1556,4,-1,0,NaN
45201,53,management,married,tertiary,no,583,no,no,cellular,17,nov,226,1,184,4,success
45202,34,admin.,single,secondary,no,557,no,no,cellular,17,nov,224,1,-1,0,NaN
45203,23,student,single,tertiary,no,113,no,no,cellular,17,nov,266,1,-1,0,NaN
45204,73,retired,married,secondary,no,2850,no,no,cellular,17,nov,300,1,40,8,failure
45205,25,technician,single,secondary,no,505,no,yes,cellular,17,nov,386,2,-1,0,NaN
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [34]:
#Choose a column with a numerical value, change its type to int64 and store in a new column.

#Change datatype of balance to int64
X.astype({'balance':'int64'})

#Store in a new column
#X.insert(16,'balanceInt64',X['balance'])

X.columns
X[:20]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,balanceInt64
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,2143
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,29
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,2
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,1506
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,1
5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN,231
6,28,management,single,tertiary,no,447,yes,yes,NaN,5,may,217,1,-1,0,NaN,447
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,NaN,5,may,380,1,-1,0,NaN,2
8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN,121
9,43,technician,single,secondary,no,593,yes,no,NaN,5,may,55,1,-1,0,NaN,593
10,41,admin.,divorced,secondary,no,270,yes,no,NaN,5,may,222,1,-1,0,NaN,270
11,29,admin.,single,secondary,no,390,yes,no,NaN,5,may,137,1,-1,0,NaN,390
12,53,technician,married,secondary,no,6,yes,no,NaN,5,may,517,1,-1,0,NaN,6
13,58,technician,married,NaN,no,71,yes,no,NaN,5,may,71,1,-1,0,NaN,71
14,57,services,married,secondary,no,162,yes,no,NaN,5,may,174,1,-1,0,NaN,162
15,51,retired,married,primary,no,229,yes,no,NaN,5,may,353,1,-1,0,NaN,229
16,45,admin.,single,NaN,no,13,yes,no,NaN,5,may,98,1,-1,0,NaN,13
17,57,blue-collar,married,primary,no,52,yes,no,NaN,5,may,38,1,-1,0,NaN,52
18,60,retired,married,primary,no,60,yes,no,NaN,5,may,219,1,-1,0,NaN,60
19,33,services,married,secondary,no,0,yes,no,NaN,5,may,54,1,-1,0,NaN,0

In [39]:
#Choose a column with a non-numerical value (that can act as a category), create a new column that contains the mapped values of 
#the categorical column from 0 to n-1. (E.g. Iris-Setosa is 0, Iris-versicolor is 1, Iris-virginica is 2).

#Using marital column

classification=[]

for y in X['marital']:
    if y == 'single':
        classification.append(1)
    elif y == 'married':
         classification.append(2)
    else:
        classification.append(0)

X.insert(17,'maritalClassification',classification)

X[:10]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,balanceInt64,maritalClassification
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,2143,2
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,29,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,2,2
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,1506,2
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,1,1
5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN,231,2
6,28,management,single,tertiary,no,447,yes,yes,NaN,5,may,217,1,-1,0,NaN,447,1
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,NaN,5,may,380,1,-1,0,NaN,2,0
8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN,121,2
9,43,technician,single,secondary,no,593,yes,no,NaN,5,may,55,1,-1,0,NaN,593,1

In [41]:
#Create a column that would have the value YES or NO depending on a conditional statement you will create 
#based on values in the dataset. (E.g. "Age > 18 == Adult | YES OR NO")

#Using marital column

classification=[]

for y in X['balance']:
    if y >= 1000:
        classification.append("YES")
    else:
        classification.append("NO")

X.insert(18,'balanceAbove1000',classification)

X[:20]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,balanceInt64,maritalClassification,balanceAbove1000
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,2143,2,YES
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,29,1,NO
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,2,2,NO
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,1506,2,YES
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,1,1,NO
5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN,231,2,NO
6,28,management,single,tertiary,no,447,yes,yes,NaN,5,may,217,1,-1,0,NaN,447,1,NO
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,NaN,5,may,380,1,-1,0,NaN,2,0,NO
8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN,121,2,NO
9,43,technician,single,secondary,no,593,yes,no,NaN,5,may,55,1,-1,0,NaN,593,1,NO
10,41,admin.,divorced,secondary,no,270,yes,no,NaN,5,may,222,1,-1,0,NaN,270,0,NO
11,29,admin.,single,secondary,no,390,yes,no,NaN,5,may,137,1,-1,0,NaN,390,1,NO
12,53,technician,married,secondary,no,6,yes,no,NaN,5,may,517,1,-1,0,NaN,6,2,NO
13,58,technician,married,NaN,no,71,yes,no,NaN,5,may,71,1,-1,0,NaN,71,2,NO
14,57,services,married,secondary,no,162,yes,no,NaN,5,may,174,1,-1,0,NaN,162,2,NO
15,51,retired,married,primary,no,229,yes,no,NaN,5,may,353,1,-1,0,NaN,229,2,NO
16,45,admin.,single,NaN,no,13,yes,no,NaN,5,may,98,1,-1,0,NaN,13,1,NO
17,57,blue-collar,married,primary,no,52,yes,no,NaN,5,may,38,1,-1,0,NaN,52,2,NO
18,60,retired,married,primary,no,60,yes,no,NaN,5,may,219,1,-1,0,NaN,60,2,NO
19,33,services,married,secondary,no,0,yes,no,NaN,5,may,54,1,-1,0,NaN,0,2,NO